version: "3.9"

services:
  backend:
    image: ghcr.io/nataliaandrade12/m324_nataliaanina-backend:latest
    container_name: todo-backend
    ports:
      - "8081:8080"

  frontend:
    image: ghcr.io/nataliaandrade12/m324_nataliaanina-frontend:latest
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend