name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Frontend builden
        run: npm run build

  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Maven Wrapper ausführbar machen
        run: chmod +x mvnw

      - name: Maven Build ausführen
        run: ./mvnw clean package